{
 "title": "Python(Granian) APM",
 "description": "Automatic observability stack for Granian with OpenTelemetry: instead of exposing /metrics, all traces, metrics, and logs are collected automatically through OTEL and sent to Grafana LGTM (Loki, Grafana, Tempo, Prometheus), with optional S3 persistence and an optimized Docker setup.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus_ds", "label": "Metrics", "query": "prometheus" },
   { "name": "tempo_datasource", "label": "Traces", "query": "tempo" },
   { "name": "loki_ds", "label": "Logs", "query": "loki" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket,job)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Service Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(http_request_duration_seconds_count{job=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{job=\"$service_name\", path!=\"/metrics\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, path) (http_request_duration_seconds_sum{job=\"$service_name\"}) / (sum by(method, path) (http_request_duration_seconds_count{job=\"$service_name\"}))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{job=\"$service_name\", path!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{job=\"$service_name\", http_status_code=~\"5.*\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path) (http_server_duration_milliseconds_count{job=\"$service_name\", http_status_code=~\"2.*\", path!=\"/metrics\"}) / sum by(path) (http_server_duration_milliseconds_count{job=\"$service_name\", path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path) (http_server_duration_milliseconds_count{job=\"$service_name\", http_status_code=~\"5.*\", path!=\"/metrics\"}) / sum by(path) (http_server_duration_milliseconds_count{job=\"$service_name\", path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"$service_name\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{job=\"$service_name\", path!=\"/metrics\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{job=\"$service_name\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Trace Logs",
   "type": "table",
   "description": "Traces containing a span emitted by the service",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$service_name\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(type) (rate({job=\"minha-stack_webflux-app.1.ifdr9h0t3gah47fq75gdnm5lj\"} | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>] - <msg>` | type != `` |= `$log_keyword` [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Log of All Granian App",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"\"} | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>] - <msg>` | line_format `{{.service_name}}\\t{{.type}}\\t trace_id={{.trace_id}}\\t {{.msg}}` |= `$log_keyword`"
    }
   ]
  },
  {
   "title": "Total Async Processes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(asyncio_process_duration_seconds_count{job=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "AsyncIO Processes",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 39 },
   "targets": [
    {
     "expr": "asyncio_process_duration_seconds_count{job=\"$service_name\"}"
    }
   ]
  },
  {
   "title": "Total DB Connections Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_client_connections_usage{job=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Active DB Connections",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 44 },
   "targets": [
    {
     "expr": "db_client_connections_usage{job=\"$service_name\"}"
    }
   ]
  }
 ]
}