POST http://localhost:8000/cotador

{
    "valor": 10,
    "empresa": "eeeeeee"
}


###


GET http://localhost:8000/user?id=6815743912fe6b4b94acb739


###


GET http://localhost:8000/user/6815743912fe6b4b94acb739


###

GET http://localhost:8000/cotadores

###


GET http://localhost:8000/openapi.json
