POST http://localhost:8000/cotador

{
    "valor": 10,
    "empresa": "eeeeeee"
}


###


GET http://localhost:8000/cotador?id=6824a20df7dd58da13144a72


###


GET http://localhost:8000/cotadores

###


GET http://localhost:8000/