POST http://localhost:8000/cotador

{
    "valor": 10,
    "empresa": "tetertretre"
}


###


GET http://localhost:8000/cotador?id=6814f386eda90f420dccf22f


###


GET http://localhost:8000/cotadores
