POST http://localhost:8000/users

{
    "valor": 10,
    "empresa": "eeeeeee"
}


###


GET http://localhost:8000/users?id=6818c5858bafb63c530c3816


###


GET http://localhost:8000/user/6818c5858bafb63c530c3816


###

GET http://localhost:8000/cotadores

###


GET http://localhost:8000/openapi.json
