POST http://localhost:8000/users

{
    "valor": 10,
    "empresa": "eeeeeee"
}


###


GET http://localhost:8000/users?id=692251538acbe725826f7b43


###

GET http://localhost:8001/users_all

###


GET http://localhost:8000/openapi.json
